FROM nginx:alpine

# Kopiranje vaših HTML in JavaScript datotek v mesto, ki ga nginx uporablja za serviranje vsebine
COPY . /usr/share/nginx/html

# Izpostavitev porta, na katerem nginx sprejema zahteve
EXPOSE 3000