name: Python app

on:
  schedule:
    - cron: '0 * * * *'  
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc dvc[s3]
      - name: Configure DVC Remote and pull
        run: |
          dvc remote add origin s3://dvc -f
          dvc remote modify origin endpointurl https://dagshub.com/CesarMitja/IIS_2.s3
          dvc remote modify origin --local access_key_id ${{ secrets.DVC_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DVC_SECRET_ACCESS_KEY }}
          dvc pull --force
      - name: Test with pytest
        run: pytest

  fetch-and-process-data:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests datetime pathlib pandas dvc dvc[s3]
      - name: Setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Configure DVC Remote and pull
        run: |
          dvc remote add origin s3://dvc -f
          dvc remote modify origin endpointurl https://dagshub.com/CesarMitja/IIS_2.s3
          dvc remote modify origin --local access_key_id ${{ secrets.DVC_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DVC_SECRET_ACCESS_KEY }}
          dvc pull -f

      - name: Fetch data
        run: python src/data/Fetch_data.py
      - name: Process data
        run: python src/data/Process_data.py


      - name: Setup auto stage and add data with DVC
        run: |
          dvc config core.autostage true
          dvc add data/raw/kolesa.csv
          dvc add data/raw/vreme.csv
          dvc add data/processed/data_for_prediction.csv
          git add .
          git commit -m "Update data" -a || echo "No changes to commit"
          git push
          dvc push 

  build-and-run-docker:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests datetime pathlib pandas dvc dvc[s3]
      
      - name: Configure DVC Remote and pull
        run: |
          dvc remote add origin s3://dvc -f
          dvc remote modify origin endpointurl https://dagshub.com/CesarMitja/IIS_2.s3
          dvc remote modify origin --local access_key_id ${{ secrets.DVC_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DVC_SECRET_ACCESS_KEY }}
          dvc pull --force


      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cesi212314/web_service_iis:latest
      - name: Build and push UI Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/client
          file: ./src/client/Dockerfile
          push: true
          tags: cesi212314/user_interface_iis:latest