name: Python application test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install poetry pytest flask pandas torch flask_cors joblib joblib scikit-learn numpy
    - name: Test with pytest
      run: pytest
